jobs:
  - job: PythonQuality
    displayName: Python tests
    pool:
      name: mlops-agent-pool

    steps:
      - checkout: self

      - script: |
          set -e
          python3 --version

          sudo apt-get update
          sudo apt-get install -y python3-pip python3-venv

          python3 -m pip install --upgrade pip
          python3 -m pip install -e .[dev]
          pytest -q
        displayName: Install and test