jobs:
  - job: PythonQuality
    displayName: Python tests
    pool:
      name: mlops-agent-pool

    steps:
      - checkout: self

      - script: |
          set -e
          python3 --version

          # Install dependencies (only once needed ideally)
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-venv

          # Create virtual environment
          python3 -m venv .venv
          source .venv/bin/activate

          # Install dependencies inside venv
          pip install --upgrade pip
          pip install -e .[dev]

          pytest -q
        displayName: Install and test