parameters:
  environmentName: dev
jobs:
  - deployment: TerraformApply
    environment: ${{ parameters.environmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: TerraformInstaller@1
              inputs: { terraformVersion: 1.6.6 }
            - script: |
                cd infra
                terraform init
                terraform apply -auto-approve -var-file=environments/${{ parameters.environmentName }}.tfvars
              displayName: Terraform apply
