trigger:
  branches:
    include: [ main ]

stages:
  - stage: Quality
    jobs:
      - template: templates/python-quality.yml
  - stage: Build
    dependsOn: Quality
    jobs:
      - template: templates/build-and-push.yml
