trigger:
  branches:
    include: [ main ]

stages:
  - stage: ValidateAndPlan
    jobs:
      - template: templates/terraform-validate-plan.yml
        parameters:
          environmentName: dev
  - stage: Apply
    dependsOn: ValidateAndPlan
    jobs:
      - template: templates/terraform-apply.yml
        parameters:
          environmentName: dev
