trigger: none

stages:
  - stage: TrainRegister
    jobs:
      - template: templates/aml-train-register.yml
  - stage: DeployAKS
    dependsOn: TrainRegister
    jobs:
      - template: templates/deploy-aks.yml
  - stage: SmokeTest
    dependsOn: DeployAKS
    jobs:
      - template: templates/smoke-test.yml
